# Generated by Django 5.1.6 on 2025-02-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
