# Generated by Django 5.1.6 on 2025-02-16 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='due_date',
        ),
    ]
