# Generated by Django 5.1.6 on 2025-02-19 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_remove_transaction_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='book',
            new_name='bookid',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='student',
            new_name='studentid',
        ),
    ]
