# Generated by Django 5.1.6 on 2025-02-19 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0001_initial'),
        ('books', '0002_book_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authorid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Author.author'),
        ),
    ]
